name: Build Main

on:
  release:
    types: [published]

  workflow_dispatch:

env:
  owner: ObsidianLabs
  own_components: eth-components
  share_components: base-components
  project_build: eth
  project_project: eth
  project_name: Black IDE
  project_build_script: yarn && yarn dist
  os_matrix: '[\"macos-latest\", \"ubuntu-18.04\", \"windows-2019\"]'
  enable_auth: false
  premium_editor: ../premium-editor

jobs:
  # Generate matrix for the following steps
  generate-matrix:
    runs-on: ubuntu-18.04

    steps:
      - name: Generate os matrix
        id: set-os-matrix
        run: echo ::set-output name=os::${{ env.os_matrix }}

      - name: Generate component matrix
        id: set-component-matrix
        run: echo ::set-output name=component::[\"${{ env.own_components }}\", \"${{ env.share_components }}\"]

    outputs:
      os: ${{ steps.set-os-matrix.outputs.os }}
      component: ${{ steps.set-component-matrix.outputs.component }}

  # Extract version
  versions:
    runs-on: ubuntu-18.04

    steps:
      - name: Get ${{ env.project_name }} version
        id: version
        shell: bash
        run: |
          echo ::set-output name=BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=VERSION::${GITHUB_REF##*[\/v]}
          if [[ ${{ contains(steps.version.outputs.BRANCH, 'rc') }} ]]; then
            echo ::set-output name=BRANCH::release
          fi
          if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo ::set-output name=BRANCH::master
          fi
          echo version:  ${{ steps.version.outputs.BRANCH }}
          echo branch: ${{ steps.version.outputs.VERSION }}

    outputs:
      branch: ${{ steps.version.outputs.BRANCH }}
      version: ${{ steps.version.outputs.VERSION }}
      v_version: v${{ steps.version.outputs.VERSION }}
      component_version: v${{ steps.version.outputs.VERSION }}-${{ env.project_build }}
      new_release: ${{ steps.version.outputs.BRANCH != 'master' && steps.version.outputs.BRANCH != 'develop' }}
      rc_release: ${{ contains(steps.version.outputs.BRANCH, 'rc') }}

  # Build and release
  release:
    needs: [generate-matrix, versions]

    strategy:
      matrix:
        os: ${{ fromJson(needs.generate-matrix.outputs.os) }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Checkout ${{ env.share_components }}
        uses: actions/checkout@v2
        with:
          repository: ${{ env.owner }}/${{ env.share_components }}
          ref: ${{ needs.versions.outputs.branch }}
          path: ./${{ env.share_components }}
          token: ${{ secrets.obsidians_token }}

      - name: Checkout ${{ env.own_components }}
        uses: actions/checkout@v2
        with:
          repository: ${{ env.owner }}/${{ env.own_components }}
          ref: ${{ needs.versions.outputs.branch }}
          path: ./${{ env.own_components }}
          token: ${{ secrets.obsidians_token }}

      - name: Checkout Premium Editor
        uses: actions/checkout@v2
        with:
          repository: ${{ env.owner }}/premium-editor
          ref: ${{ needs.versions.outputs.branch }}
          path: ./premium-editor
          token: ${{ secrets.obsidians_token }}

      - name: Checkout ${{ env.project_name }}
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.versions.outputs.branch }}
          path: ./studio

      - name: Install ${{ env.share_components }} submodule
        working-directory: ./${{ env.share_components }}
        run: git submodule update --init

      - name: Install ${{ env.share_components }} dependencies
        working-directory: ./${{ env.share_components }}
        run: yarn

      - name: Build ${{ env.share_components }}
        working-directory: ./${{ env.share_components }}
        run: yarn build

      - name: Install ${{ env.own_components }} submodule
        working-directory: ./${{ env.own_components }}
        run: git submodule update --init

      - name: Install ${{ env.own_components }} dependencies
        working-directory: ./${{ env.own_components }}
        run: yarn

      - name: Build ${{ env.own_components }}
        working-directory: ./${{ env.own_components }}
        run: yarn build

      - name: Install Premium Editor dependencies
        working-directory: ./premium-editor
        run: yarn

      - name: Build Premium Editor
        working-directory: ./premium-editor
        run: yarn build

      - name: Build ${{ env.project_name }}
        uses: ObsidianLabs/studio-build-action@master
        with:
          build: ${{ env.project_build }}
          project: ${{ env.project_project }}
          project_name: ${{ env.project_name }}
          build_script: ${{ env.project_build_script }}
          working-directory: ./studio
          enable_auth: ${{ env.enable_auth }}
          mac_certs: ${{ secrets.certs }}
          mac_certs_password: ${{ secrets.certs_password }}
          windows_certs: ${{ secrets.certs }}
          windows_certs_password: ${{ secrets.certs_password }}
          react_app_mixpanel_token: ${{ secrets.react_app_mixpanel_token }}
          premium_editor: ${{ env.premium_editor }}
          github_token: ${{ github.token }}

      - name: Clean up Build assets
        working-directory: ./studio/dist
        run: rm builder-debug.yml

      - name: Upload assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'studio/dist/*.(dmg|zip|exe|AppImage|yml)'
          repo-token: ${{ github.token }}
