name:                ligo-webide-backend

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- mtl
- katip
- process
- servant-server
- temporary
- text
- wai
- warp

library:
  source-dirs: src

executables:
  ligo-webide-backend:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ligo-webide-backend
    - optparse-applicative

tests:
  ligo-webide-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - http-types
    - hspec
    - hspec-expectations
    - hspec-wai
    - hspec-wai-json
    - ligo-webide-backend
    - wai-extra
