name: "Nix CI"

on:
  push:
  pull_request:


jobs:

  build-webide:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - name: Building webide
        run: nix build .#webide -L --accept-flake-config

  build-backend:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - name: Building backend
        run: nix build .#backend -L --accept-flake-config

  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - name: Running checks
        run: nix flake check . -L  --accept-flake-config
